before:
  hooks:
    - go mod tidy
changelog:
  skip: true
builds:
  - env:
      - CGO_ENABLED=0
    main: ./bin/renlfn
    goos:
      - linux
      - windows
    goarch:
      - amd64
archives:
  - format: zip