name: Draft

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  draft:
    name: Draft
    runs-on: ubuntu-latest
    steps:
      - name: Draft Release
        uses: release-drafter/release-drafter@v5.17.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
